

### Get Azure AD Token
# @name getToken
POST https://login.microsoftonline.com/9249ded8-dff5-4e90-9d80-3ae45c13ec3f/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{$dotenv AZURE_CLIENT_ID}}&client_secret={{$dotenv AZURE_CLIENT_SECRET}}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default

### Test GET Request
GET https://apim-pauth-dev-southcentralus.azure-api.net/app
Authorization: Bearer {{getToken.response.body.access_token}}
Content-Type: application/json
Ocp-Apim-Trace: true
Ocp-Apim-Subscription-Key: {{$dotenv APIM_SUBSCRIPTION_KEY}}


### Test POST Request to round-robin-weighted-v2/openai
POST https://apim-pauth-dev-southcentralus.azure-api.net/round-robin-weighted-v2/openai?deployment-id=aoai&api-version=2024-08-01-preview
Authorization: Bearer {{getToken.response.body.access_token}}
Content-Type: application/json
Ocp-Apim-Trace: true
Ocp-Apim-Subscription-Key: {{$dotenv APIM_SUBSCRIPTION_KEY}}

{
    "input": "Test input data"
}
