PUT https://management.azure.com/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Search/searchServices/{{$dotenv AZURE_SEARCH_SERVICE_NAME}}?api-version=2024-06-01-preview
Content-Type: application/json

{
    "location": "[region]",
    "sku": {
        "name": "[sku]"
    },
    "properties": {
        "replicaCount": [replica count],
        "partitionCount": [partition count],
        "hostingMode": "default"
    },
    "identity": {
        "type": "SystemAssigned"
        # "type": "UserAssigned",
        # "userAssignedIdentities": {
        #     "/subscriptions/[subscription ID]/resourcegroups/[resource group name]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/[name of managed identity]": {}
        # }
    }
}