name: '🚀 Prior Authorization - Bicep Infrastructure Deployment 🌐'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: false

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - integration/iac
    paths:
      - '.github/workflows/infra_deploy.yml'
      - 'devops/infra'

#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'devops/infra'

permissions:
  id-token: write
  contents: read

env:
  deployStackName: 'PriorAuth-Infra'
  deploymentPath: 'devops/infra/main.bicep'
  scenarioName: 'ase-multitenant'
  region: 'westus2'
  # webAppPlanSKU is the only parameter that is overridden for ASEv3
  acrContainerImage: 'mcr.microsoft.com/k8se/quickstart:latest'
  embeddingModel: '{"name": "text-embedding-3-large", "version": "1", "skuName": "Standard", "capacity": 16}'

jobs:
  prepare-environment:
    name: 'Prepare CICD Environment for Bicep Workflow'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    outputs:
      deployStackName: ${{ env.deployStackName }}
      region: ${{ env.region }}
      modulePath: ${{ env.deploymentPath }}
      bicepParamPath: ${{ env.deploymentPath }}/main.parameters.jsonc
      bicepAdditionalParams: -p embeddingModel=${{ env.embeddingModel }} -p acrContainerImage=${{ env.acrContainerImage }} --deny-settings-mode 'none'

  call-workflow-passing-data:
    name: 'Bicep CICD'
    needs: 
    - prepare-environment
    uses: ./.github/workflows/.template.bicep.yml
    with:
      deployStackName: ${{ needs.prepare-environment.outputs.deployStackName }}
      region: ${{ needs.prepare-environment.outputs.region }}
      modulePath: ${{ needs.prepare-environment.outputs.modulePath }}
      bicepParamPath: ${{ needs.prepare-environment.outputs.bicepParamPath }}
      bicepAdditionalParams: ${{ needs.prepare-environment.outputs.bicepAdditionalParams }}
      # Ensure this value is a boolean
      destroy: ${{ github.event.inputs.destroy == 'true' }}
    secrets: inherit